training:
  batch_size: 16       # Example value
  epochs: 100          # Example value
  start_epoch: 1       # Example value
  lambda_L1: 10.0      # Example value for L1 regularization weight
  lr: 0.0002           # Learning rate for Adam optimizer
  checkpoint_interval: 20  # How often to save checkpoints


data:
  train_images_dir: "data/processed/train/images"
  train_labels_dir: "data/processed/train/labels"
  val_images_dir: "data/processed/val/images"
  val_labels_dir: "data/processed/val/labels"

logging:
  log_interval: 10                 # Log frequency (in steps)
  checkpoint_interval: 5           # Frequency of saving model checkpoints

device:
  use_gpu: true                    # Enable GPU usage if available
